"""
Multi-Channel Dispatcher Module.
Formats and dispatches corporate policy responses with verifiable citations to
Slack Block Kit, Microsoft Teams Adaptive Cards, and HTML/Text Email templates.
"""

import json
import logging
import urllib.request
import urllib.parse
from datetime import datetime
from typing import Dict, Any, List, Optional

logger = logging.getLogger("utils.notifications")


def format_email_template(
    query: str,
    answer: str,
    citations: Optional[List[Dict[str, Any]]] = None,
    sender_name: str = "Synthara Policy Portal"
) -> Dict[str, str]:
    """Builds clean corporate HTML and plaintext email templates."""
    citations_list = citations or []
    
    # HTML citations list
    cit_html = ""
    if citations_list:
        cit_html = "<h4 style='color:#4f46e5;margin-top:16px;'>Verified Policy Citations:</h4><ul style='color:#64748b;font-size:12px;'>"
        for idx, c in enumerate(citations_list):
            meta = c.get("metadata", {})
            src = meta.get("source", "Document")
            page = meta.get("page", 1)
            cit_html += f"<li><strong>[{idx+1}] {src}</strong> (Page {page}) &mdash; <em>\"{c.get('text', '')[:120]}...\"</em></li>"
        cit_html += "</ul>"

    html_body = f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background-color:#0b0f19;color:#f8fafc;padding:24px;">
      <div style="max-width:600px;margin:0 auto;background:#131b2e;border:1px solid #1e293b;border-radius:16px;padding:24px;box-shadow:0 10px 25px rgba(0,0,0,0.5);">
        <h2 style="color:#818cf8;margin-top:0;">🛡️ Synthara Policy Guidance</h2>
        <div style="background:#1e293b;border-left:4px solid #6366f1;padding:12px 16px;border-radius:8px;margin-bottom:16px;">
          <p style="margin:0;font-size:13px;color:#94a3b8;"><strong>Inquiry:</strong> {query}</p>
        </div>
        <div style="font-size:14px;line-height:1.6;color:#e2e8f0;white-space:pre-wrap;">{answer}</div>
        {cit_html}
        <hr style="border:0;border-top:1px solid #334155;margin:24px 0 12px 0;">
        <p style="font-size:11px;color:#64748b;text-align:center;">Generated by {sender_name} &bull; Enterprise Policy Assistant</p>
      </div>
    </body>
    </html>
    """
    
    text_body = f"Synthara Policy Guidance\nInquiry: {query}\n\nAnswer:\n{answer}\n"
    if citations_list:
        text_body += "\nCitations:\n"
        for idx, c in enumerate(citations_list):
            src = c.get("metadata", {}).get("source", "Document")
            page = c.get("metadata", {}).get("page", 1)
            text_body += f"[{idx+1}] {src} (Page {page})\n"

    subject = f"Policy Guidance: {query[:45]}..." if len(query) > 45 else f"Policy Guidance: {query}"
    return {
        "subject": subject,
        "html_body": html_body,
        "text_body": text_body,
        "mailto_url": f"mailto:?subject={urllib.parse.quote(subject)}&body={urllib.parse.quote(text_body)}"
    }


def format_slack_block_kit(
    query: str,
    answer: str,
    citations: Optional[List[Dict[str, Any]]] = None
) -> Dict[str, Any]:
    """Generates formatted Slack Block Kit payload."""
    blocks = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": "🛡️ Policy Response | Synthara RAG", "emoji": True}
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Inquiry:* _{query}_\n\n{answer}"}
        }
    ]
    
    if citations:
        cit_text = "*Citations:*\n" + "\n".join(
            f"• *[{i+1}]* `{c.get('metadata', {}).get('source')}` (p. {c.get('metadata', {}).get('page')})"
            for i, c in enumerate(citations)
        )
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": cit_text}]
        })
        
    return {"blocks": blocks}


def format_teams_card(
    query: str,
    answer: str,
    citations: Optional[List[Dict[str, Any]]] = None
) -> Dict[str, Any]:
    """Generates MS Teams MessageCard payload."""
    facts = []
    if citations:
        for idx, c in enumerate(citations[:3]):
            facts.append({
                "name": f"Citation [{idx+1}]",
                "value": f"{c.get('metadata', {}).get('source')} (Page {c.get('metadata', {}).get('page')})"
            })

    return {
        "@type": "MessageCard",
        "@context": "https://schema.org/extensions",
        "summary": f"Policy Guidance: {query}",
        "themeColor": "4F46E5",
        "title": "🛡️ Synthara Policy Guidance",
        "sections": [{
            "activityTitle": f"**Question:** {query}",
            "text": answer,
            "facts": facts
        }]
    }


def dispatch_webhook(webhook_url: str, payload: Dict[str, Any]) -> bool:
    """Dispatches JSON payload to webhook URL."""
    try:
        data = json.dumps(payload).encode('utf-8')
        req = urllib.request.Request(
            webhook_url,
            data=data,
            headers={'Content-Type': 'application/json', 'User-Agent': 'Synthara-Policy-Bot/1.0'}
        )
        with urllib.request.urlopen(req, timeout=5) as response:
            return response.status in [200, 201, 204]
    except Exception as e:
        logger.error(f"Webhook dispatch failed: {e}")
        return False
